### ISSUE TITLE
Agendar reunião Carlla para propor parceria fluxo promoção e progressão

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/projeto-fhemig#5]
See https://github.com/automatiza-mg/imersao-scap/issues/13

@Isabelle-Fernandes, vc consegue agendar esse encontro p gente?

**Comment by Isabelle-Fernandes** [comment]
Agendado para dia 24/07 (quarta-feira) às 10:00h

**Comment by gabrielbdornas** [comment]
> Agendado para dia 24/07 (quarta-feira) às 10:00h

@Isabelle-Fernandes, quando for assim, pode fechar o Issue!
